### PR TITLE
React Testing Library Conversion

### LINKED ISSUE #54: Converting the tests from Enzyme to Testing Library.
Hi :wave:

I recognized your library when looking for a solution that allows me to check the previous pathname. :grin: 

I saw that you guys are currently using Enzyme, which itself seems to be [blocking the support of React 17+.](https://github.com/hinok/react-router-last-location/issues/46)

I and many friends are a part of the Open Source Raid Guild, a group that supports OSS projects. :blue_heart: 

Many of us work together on one large PR. :nerd_face: 

We would fork your project to our Github Team and work on our fork, and communicate with some of the maintainers closely over at Discord.

Read more about us: https://github.com/OpenSourceRaidGuild/tutorial-quest#hi-wave-welcome-to-the-open-source-raid-guild-crossed_swords

Our discord server: https://discord.gg/JczjG8su

Let us know if you've any questions, and feel free to join the Discord already, even if it is just a question. :partying_face:

### PR DESCRIPTION
**Pull request by JacobMGEvans**
Read more about us: https://github.com/OpenSourceRaidGuild/tutorial-quest#hi-wave-welcome-to-the-open-source-raid-guild-crossed_swords

Our Discord server: https://discord.gg/JczjG8su

resolves #54

### CODE REVIEW

**Comment by JacobMGEvans** [comment]
Pretty close to done. We had it at 100% at one point lol

**Comment by JacobMGEvans** [comment]
Done. 100% coverage and 100% React Testing Library. We also removed the Enzyme dependencies

**Comment by JacobMGEvans** [comment]
@hinok  It is ready for review.  
Some test structure changes. 
- Moved Provider tests into `useLastLocation()`
- Tested lastLocation context Getter in rerendered test
using it to check context key & pathname as well as the hook

**Comment by hinok** [comment]
@JacobMGEvans I will take a look today evening after work, many thanks!

**Comment by JacobMGEvans** [comment]
@hinok just a friendly reminder, this PR is ready 😄

**Comment by joealden** [comment]
@hinok any update on this?

**Comment by hinok** [comment]
@JacobMGEvans Many thanks 👏👏👏👏👏👏  Merging.
I will do a small clean up later today.

**Pull request merged**
